### ISSUE TITLE
oktaAddUserAdminTarget

### ISSUE THREAD

**Issue by vikashdaya** [mbegan/Okta-PSModule#12]
Hi Matt

This cmdlet doesn't work.  I get the following error:
E0000022 ; The endpoint does not support the provided HTTP method
At C:\Program Files\WindowsPowerShell\Modules\okta\Okta.psm1:34 char:5
+     throw $formatError
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FormatException
    + FullyQualifiedErrorId : E0000022 ; The endpoint does not support the provided HTTP method

**Comment by vikashdaya** [comment]
Changed the Method to "PUT" and now I get the following error:
E0000091 ; The provided role type was not the same as required role type.
At C:\Program Files\WindowsPowerShell\Modules\okta\Okta.psm1:34 char:5
+     throw $formatError
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FormatException
    + FullyQualifiedErrorId : E0000091 ; The provided role type was not the same as required role type.

**Comment by vikashdaya** [comment]
tried using the "oktaAddUsertoRoles" cmdlet to assign User Admin role and target to a group.  Role assignment works but group targeting doesn't.

**Comment by mbegan** [comment]
Roles are only able to be assigned to users
