### ISSUE TITLE
How to get rid of Verbose messages when using the Okta cmdlets

### ISSUE THREAD

**Issue by nemo5555** [mbegan/Okta-PSModule#16]
Hi,
Can you please advise how do I get rid of the VERBOSE messages when using the cmdlets ?
I have tried using  "-Verbose:$false" and " $VerbosePreference = "continue" but had no success in suppressing the VERBOSE messages like these:

VERBOSE: GET https://xxxx.okta.com/api/v1/users/XXXXXXXX/groups with 0-byte payload
VERBOSE: received -1-byte response of content type application/json;charset=UTF-8

**Comment by mbegan** [comment]
Modify the Okta_org.ps1 file

```powershell
<# Okta_org.ps1 #>
# Verbose will print various informative messages
[Boolean]$oktaVerbose = $false
```

or issue this command from the powershell prompt

```powershell
$oktaVerbose = $false
```

**Comment by nemo5555** [comment]
Thanks for the quick response.
