### ISSUE TITLE
ConvertFrom-JSON InputObject parameter returns conversion error

### ISSUE THREAD

**Issue by weigh2tall** [mbegan/Okta-PSModule#17]
Going to admit to being a newbie with the module, but it is definitely looking promising.  When I run a command (for example OktaAddUserIDtoGroupID), I get this response:

`WARNING: Cannot convert 'System.Byte[]' to the type 'System.String' required by parameter 'InputObject'. Specified method is not supported.`

I may be misdiagnosing where the error is arising from.

**Comment by mbegan** [comment]
Good catch, this may have been lingering around for awhile and i've just been ignoring the error ;-)  I just pushed a fix.

**Comment by weigh2tall** [comment]
Thanks!
