### ISSUE TITLE
Error running initial command

### ISSUE THREAD

**Issue by gharryjr** [mbegan/Okta-PSModule#19]
I get:

Cannot index into a null array.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Okta\Okta.psm1:552 char:45
+         $_c = $headers.Add($alt,$altHeaders[ <<<< $alt])
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

When I run:

ps c:\> oktaGetUserbyID -oOrg prev -uid "myuserid"

I'm new to running Okta API calls in PS, so I am not sure what may be happening here .

**Comment by noeffort3** [comment]
Hi Matt,

I just left you a voicemail on your cellie.  I am seeing error :)

Both prod and prev as values for -oOrg, whether explicit -oOrg 'prod' (or 'prev') or via variable inclusion within xyz script as:
$oOrg = 'prev'  and used inline in already previously correctly running scripts

/me thinks OKTA backend changed some kind of value? 

Cheers!

**Comment by mbegan** [comment]
@gharryjr   I've been unable to replicate the error you are encountering so if you can provide more context (see prev note).

@noeffort3  Hi RG.  While the top level error is similar it looks like you are facing something entirely different, it also looks like you are running an old version of the module (line 1047 isn't a part of _oktaNewCall anymore).  Can you also provide some additional context (same as the note above for @gharryjr) but open a new issue.

**Comment by gharryjr** [comment]
Additional info highlighted.

**Comment by mbegan** [comment]
Ah!

I think i see the issue, you are running powershell version 2 and it doesn't support some of the basic stuff this module is doing.

I used to have a minimum version check in this package but i had to take it out because of the way it is evaluated when running in different toolkits like vscode.

I believe the minimum powershell version is 3.0 but i'd highly recommend upgrading to version 4.x or newer.  [Try This](https://www.microsoft.com/en-us/download/details.aspx?id=54616)

**Comment by gharryjr** [comment]
Awesome…the update of PS worked for me.  Thanks for the quick feedback.

**Comment by mbegan** [comment]
Addressed with documentation in commit b72a506

**Comment by noeffort3** [comment]
Hmm, interesting... for some reason when i run "git" it refreshes "successfully", just not "correctly" it keeps pulling down the old Nov 17, 2017 set.  Used zip.  Will try :)  Cheers, see ya at Oktane!

**Comment by mbegan** [comment]
with a local git repo the command to fetch and merge changes from the remote repo (github) would be would be `git pull`

**Comment by noeffort3** [comment]
Yeah, Git-Dummy was using git fetch :P
