### ISSUE TITLE
oktaListGroupRules limited to 50 rules

### ISSUE THREAD

**Issue by wysiwyg08620** [mbegan/Okta-PSModule#36]
I am attempting to export all my Okta group rules (I have more than 50) but when I attempt to use the 'oktaListGroupRules' command it only returns 50 rules.  I've attempted to run with the "-limit 100", but that still returns 50 rules.  Any insight/help is greatly appreciated.

Dave.

**Comment by mbegan** [comment]
just pushed a code fix, download the latest and try again.
