### ISSUE TITLE
Change the bulk users status suspended to deprovisioned

### ISSUE THREAD

**Issue by Saikishore031** [mbegan/Okta-PSModule#40]
Hi Friend,

Could you please provide me the powershell script of bulk users changing the status from suspended to deprovisioning.

I can suspend the user with the help of ‘OKTASUSPENDUSERBYID’ but only one user i can suspend😔. So, could you please provide me the powershell script to change the status of bulk users. Please do the needful.

**Comment by mbegan** [comment]
Take a look at my [deleteDeactivatedUsers.ps1](https://github.com/mbegan/Okta-Scripts/blob/master/deleteDeactivatedUsers.ps1) script (and other scripts in that repo) for some examples of how to work through collections of users to perform bulk actions.

It won't do exactly what you are asking but should give you a good idea of how to move forward.
