### ISSUE TITLE
Trying to list all deprovisioned users but getting error

### ISSUE THREAD

**Issue by danxero** [mbegan/Okta-PSModule#41]
Hi,
I am trying to use your module to list all our deprovisioned, but I get the following error.
As you can see, I tried a few other commands as well, with no luck either.
![image](https://user-images.githubusercontent.com/50723502/57896206-eab80e80-7892-11e9-94bd-01f1524bb0ec.png)

I guess it's something I have not configured properly, any ideas?

**Comment by mbegan** [comment]
What version of powershell are you running?

**Comment by noeffort3** [comment]
I see this error when i know I haven’t refreshed the Okta module. May just
need to git or re-download Matt’s module.

**Comment by danxero** [comment]
Sorry, I was away for a couple of days.  
I'll test again now by downloading the module again.

I am on version 5:
![image](https://user-images.githubusercontent.com/50723502/58440623-a47a6f00-811e-11e9-9b7d-c63ece7dc512.png)

**Comment by danxero** [comment]
OK, I managed to get it working on a different server - so maybe it was a version issue.  

Thanks for the suggestions, and for the work putting this module together!
