### ISSUE TITLE
Helpdesk Script

### ISSUE THREAD

**Issue by AlexNicastro** [mbegan/Okta-PSModule#5]
Hello,

 I am trying to write an okta script for our helpdesk.  I am trying to do the following:

1. Activate a user
2. Confirm a user

Once I activate a user I noticed the user goes into Password Reset.  I think its cuz the user was in disabled users.  I am trying to find a user to test with, I think when i reactivate the user it wont go into password reset.  Instead of going into Okta -> Directory -> Directory Integration -> Active Directory ->  Import -> 1 Partial Okta User Match Found -> Confirm

Is there a way to confirm a partial okta user in powershell.  I appreciate your help and sorry for the newb question.  

Thanks,
Alex Nicastro

**Comment by mbegan** [comment]
Hi Alex,

I haven't looked recently but i do not believe there is a way to match/confirm users from the directory import.

That said i think you can get past the issue you are facing but enabling a feature flag in your okta Org.

I don't remember exactly what it is called but you can check with Okta support and I think they will know what you are after.  Basically you want reactivated / enabled AD users to automatically confirm.  We have this on in our org and it allows me to move past the issue you are facing.
